# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'note.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Note_Dialog(object):
    def setupUi(self, Note_Dialog):
        Note_Dialog.setObjectName("Note_Dialog")
        Note_Dialog.resize(300, 114)
        Note_Dialog.setMinimumSize(QtCore.QSize(300, 114))
        Note_Dialog.setMaximumSize(QtCore.QSize(300, 114))
        self.label = QtWidgets.QLabel(Note_Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 131, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Note_Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 261, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Note_Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 80, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(Note_Dialog)
        self.checkBox.setGeometry(QtCore.QRect(20, 60, 70, 17))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(Note_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Note_Dialog)

    def retranslateUi(self, Note_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Note_Dialog.setWindowTitle(_translate("Note_Dialog", "Dialog"))
        self.label.setText(_translate("Note_Dialog", "Insert a note (if needed)"))
        self.pushButton.setText(_translate("Note_Dialog", "Ok"))
        self.pushButton.setShortcut(_translate("Note_Dialog", "Return"))
        self.checkBox.setText(_translate("Note_Dialog", "Review"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Note_Dialog = QtWidgets.QDialog()
    ui = Ui_Note_Dialog()
    ui.setupUi(Note_Dialog)
    Note_Dialog.show()
    sys.exit(app.exec_())
