# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Record(object):
    def setupUi(self, Record):
        Record.setObjectName("Record")
        Record.resize(380, 66)
        self.pushButton = QtWidgets.QPushButton(Record)
        self.pushButton.setGeometry(QtCore.QRect(150, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Record)
        self.label.setGeometry(QtCore.QRect(20, 5, 341, 21))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Record)
        QtCore.QMetaObject.connectSlotsByName(Record)

    def retranslateUi(self, Record):
        _translate = QtCore.QCoreApplication.translate
        Record.setWindowTitle(_translate("Record", "Dialog"))
        self.pushButton.setText(_translate("Record", "OK"))
        self.label.setText(_translate("Record", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Record = QtWidgets.QDialog()
    ui = Ui_Record()
    ui.setupUi(Record)
    Record.show()
    sys.exit(app.exec_())
