# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Testlist_DIalog(object):
    def setupUi(self, Testlist_DIalog):
        Testlist_DIalog.setObjectName("Testlist_DIalog")
        Testlist_DIalog.resize(360, 245)
        Testlist_DIalog.setMinimumSize(QtCore.QSize(360, 245))
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Testlist_DIalog)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(218, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(Testlist_DIalog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(Testlist_DIalog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(Testlist_DIalog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(Testlist_DIalog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)

        self.retranslateUi(Testlist_DIalog)
        QtCore.QMetaObject.connectSlotsByName(Testlist_DIalog)

    def retranslateUi(self, Testlist_DIalog):
        _translate = QtCore.QCoreApplication.translate
        Testlist_DIalog.setWindowTitle(_translate("Testlist_DIalog", "Dialog"))
        self.pushButton_3.setText(_translate("Testlist_DIalog", "Cancel"))
        self.pushButton_2.setText(_translate("Testlist_DIalog", "Default"))
        self.pushButton.setText(_translate("Testlist_DIalog", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Testlist_DIalog = QtWidgets.QDialog()
    ui = Ui_Testlist_DIalog()
    ui.setupUi(Testlist_DIalog)
    Testlist_DIalog.show()
    sys.exit(app.exec_())
