# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(272, 189)
        About.setMinimumSize(QtCore.QSize(272, 189))
        About.setMaximumSize(QtCore.QSize(272, 189))
        self.label = QtWidgets.QLabel(About)
        self.label.setGeometry(QtCore.QRect(40, -15, 191, 101))
        self.label.setMinimumSize(QtCore.QSize(191, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/vortex_logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(About)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 251, 110))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "Dialog"))
        self.label_2.setText(_translate("About", "<html><head/><body><p align=\"center\">VoRTEx v0.5.4a - Voice Recognition Test Execution</p></body></html>"))
        self.label_3.setText(_translate("About", "<html><head/><body><p align=\"center\">\'From testers, for testers\'</p></body></html>"))
        self.label_4.setText(_translate("About", "Os: Windows"))
        self.label_5.setText(_translate("About", "(c) Jul. 2021 - Alberto Occelli"))
        self.label_6.setText(_translate("About", "email: albertoccelli@gmail.com"))
        self.label_7.setText(_translate("About", "https://github.com/albertoccelli/VoRTEx"))
from . import gui_imgs_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    About = QtWidgets.QDialog()
    ui = Ui_About()
    ui.setupUi(About)
    About.show()
    sys.exit(app.exec_())
