# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Splash(object):
    def setupUi(self, Splash):
        Splash.setObjectName("Splash")
        Splash.resize(722, 322)
        Splash.setMinimumSize(QtCore.QSize(722, 322))
        Splash.setMaximumSize(QtCore.QSize(722, 322))
        self.label = QtWidgets.QLabel(Splash)
        self.label.setGeometry(QtCore.QRect(-20, -90, 751, 411))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(Splash)
        self.progressBar.setGeometry(QtCore.QRect(0, 300, 731, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(Splash)
        self.label_2.setGeometry(QtCore.QRect(10, 283, 701, 20))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(Splash)
        self.layoutWidget.setGeometry(QtCore.QRect(166, 180, 391, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)

        self.retranslateUi(Splash)
        QtCore.QMetaObject.connectSlotsByName(Splash)

    def retranslateUi(self, Splash):
        _translate = QtCore.QCoreApplication.translate
        Splash.setWindowTitle(_translate("Splash", "Dialog"))
        self.label_2.setText(_translate("Splash", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.label_3.setText(_translate("Splash", "v.0.5.4 alpha"))
        self.label_4.setText(_translate("Splash", "<html><head/><body><p align=\"center\">\'From testers, for testers\'</p></body></html>"))
        self.label_6.setText(_translate("Splash", "(c) Jul. 2021 - Alberto Occelli"))
        self.label_7.setText(_translate("Splash", "email: albertoccelli@gmail.com"))
        self.label_8.setText(_translate("Splash", "https://github.com/albertoccelli/VoRTEx"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Splash = QtWidgets.QDialog()
    ui = Ui_Splash()
    ui.setupUi(Splash)
    Splash.show()
    sys.exit(app.exec_())
